In [2]:
import csv
import pandas as pd
data = pd.read_csv('LoxodontaAfricana1990-2016.csv')

In [3]:
data

,Year,App.,Taxon,Class,Order,Family,Genus,Importer,Exporter,Origin,Importer reported quantity,Exporter reported quantity,Term,Unit,Purpose,Source
0,1990,I,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,AE,IT,ZW,NaN,4,shoes,NaN,NaN,W
1,1990,I,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,AG,ZW,NaN,NaN,1,ivory carvings,NaN,NaN,NaN
2,1990,I,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,AO,ZW,NaN,NaN,1,ivory carvings,NaN,NaN,NaN
3,1990,I,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,AR,ZA,NaN,NaN,1,ivory carvings,NaN,P,NaN
4,1990,I,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,AR,ZA,NaN,NaN,6,leather items,NaN,P,NaN
5,1990,I,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,AR,ZA,NaN,NaN,24,tusks,kg,P,NaN
6,1990,I,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,AR,ZA,NaN,2,NaN,tusks,NaN,P,W
7,1990,I,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,AT,BW,NaN,NaN,1,ivory carvings,sets,P,NaN
8,1990,I,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,AT,CH,KE,1,NaN,ivory carvings,sets,P,NaN
9,1990,I,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,AT,CH,XX,1,NaN,ivory carvings,sets,P,NaN
10,1990,I,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,AT,CH,ZW,NaN,1,leather products (small),NaN,NaN,NaN
11,1990,I,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,AT,DE,KE,NaN,1600,ivory carvings,sets,T,O
12,1990,I,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,AT,DE,KE,23,NaN,ivory carvings,sets,T,NaN
13,1990,I,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,AT,DE,XX,NaN,700,ivory carvings,g,T,O
14,1990,I,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,AT,DE,XX,NaN,400,ivory carvings,sets,P,O
15,1990,I,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,AT,DE,ZA,NaN,850,ivory carvings,sets,T,O
16,1990,I,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,AT,DE,ZA,2,NaN,ivory carvings,sets,T,NaN
17,1990,I,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,AT,ET,NaN,NaN,41,tusks,kg,H,NaN
18,1990,I,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,AT,ET,NaN,2,NaN,tusks,NaN,P,NaN
19,1990,I,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,AT,IT,BW,NaN,3,leather products (small),NaN,NaN,NaN
20,1990,I,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,AT,IT,KE,1,NaN,ivory carvings,sets,T,NaN
21,1990,I,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,AT,IT,ZW,3,NaN,live,NaN,Q,NaN
22,1990,I,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,AT,IT,ZW,NaN,120,leather products (small),NaN,NaN,O
23,1990,I,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,AT,IT,ZW,NaN,2,leather items,NaN,NaN,O
24,1990,I,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,AT,TZ,NaN,6,NaN,ears,NaN,P,NaN
25,1990,I,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,AT,TZ,NaN,11,NaN,feet,NaN,P,NaN
26,1990,I,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,AT,TZ,NaN,7,NaN,skins,NaN,P,NaN
27,1990,I,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,AT,TZ,NaN,1,NaN,tails,NaN,P,NaN
28,1990,I,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,AT,TZ,NaN,1,NaN,trophies,NaN,P,NaN
29,1990,I,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,AT,TZ,NaN,18,NaN,tusks,kg,P,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31404,2015,II,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,US,ZA,NaN,4,NaN,leather products (small),NaN,H,W
31405,2015,II,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,US,ZA,NaN,54,NaN,skin pieces,NaN,H,W
31406,2015,II,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,US,ZA,NaN,317,NaN,skin pieces,NaN,T,W
31407,2015,II,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,US,ZA,NaN,3,NaN,skulls,NaN,H,W
31408,2015,II,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,US,ZA,NaN,6,NaN,tails,NaN,H,W
31409,2015,II,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,US,ZA,NaN,44,NaN,trophies,NaN,H,W
31410,2015,II,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,US,ZA,NaN,15,NaN,tusks,NaN,H,W
31411,2015,II,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,US,ZW,ZA,4,NaN,ears,NaN,H,W
31412,2015,II,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,US,ZW,ZA,4,NaN,leather products (small),NaN,H,W
31413,2015,II,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,US,ZW,ZA,1,NaN,trophies,NaN,H,W
31414,2015,II,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,US,ZW,ZA,1,NaN,tusks,NaN,H,W
31415,2015,II,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,US,ZW,NaN,17,NaN,bones,NaN,H,W
31416,2015,II,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,US,ZW,NaN,2,NaN,bone pieces,NaN,H,W
31417,2015,II,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,US,ZW,NaN,35,NaN,ears,NaN,H,W
31418,2015,II,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,US,ZW,NaN,39,NaN,ears,NaN,T,W
31419,2015,II,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,US,ZW,NaN,38,NaN,feet,NaN,H,W
31420,2015,II,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,US,ZW,NaN,129,NaN,hair,NaN,P,I
31421,2015,II,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,US,ZW,NaN,62,NaN,leather products (large),NaN,H,W
31422,2015,II,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,US,ZW,NaN,66,NaN,leather products (small),NaN,H,W
31423,2015,II,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,US,ZW,NaN,4,NaN,sides,NaN,T,W
31424,2015,II,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,US,ZW,NaN,14,NaN,skins,NaN,P,W
31425,2015,II,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,US,ZW,NaN,436,NaN,skins,NaN,T,W
31426,2015,II,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,US,ZW,NaN,63,NaN,skin pieces,NaN,H,W
31427,2015,II,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,US,ZW,NaN,2833,NaN,skin pieces,NaN,T,W
31428,2015,II,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,US,ZW,NaN,4,NaN,skulls,NaN,H,W
31429,2015,II,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,US,ZW,NaN,6,NaN,tails,NaN,H,W
31430,2015,II,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,US,ZW,NaN,2,NaN,trophies,NaN,H,I
31431,2015,II,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,US,ZW,NaN,29,NaN,trophies,NaN,H,W
31432,2015,II,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,US,ZW,NaN,28,NaN,tusks,NaN,H,W
31433,2015,II,Loxodonta africana,Mammalia,Proboscidea,Elephantidae,Loxodonta,US,ZW,NaN,1,NaN,tusks,NaN,P,I

In [4]:
exp_imp_year = data[['Year','Importer','Exporter']]

In [5]:
exp_imp_year

       Year Importer Exporter
0      1990       AE       IT
1      1990       AG       ZW
2      1990       AO       ZW
3      1990       AR       ZA
4      1990       AR       ZA
5      1990       AR       ZA
6      1990       AR       ZA
7      1990       AT       BW
8      1990       AT       CH
9      1990       AT       CH
10     1990       AT       CH
11     1990       AT       DE
12     1990       AT       DE
13     1990       AT       DE
14     1990       AT       DE
15     1990       AT       DE
16     1990       AT       DE
17     1990       AT       ET
18     1990       AT       ET
19     1990       AT       IT
20     1990       AT       IT
21     1990       AT       IT
22     1990       AT       IT
23     1990       AT       IT
24     1990       AT       TZ
25     1990       AT       TZ
26     1990       AT       TZ
27     1990       AT       TZ
28     1990       AT       TZ
29     1990       AT       TZ
...     ...      ...      ...
31404  2015       US       ZA
31405  2015       US       ZA
31406  2015       US       ZA
31407  2015       US       ZA
31408  2015       US       ZA
31409  2015       US       ZA
31410  2015       US       ZA
31411  2015       US       ZW
31412  2015       US       ZW
31413  2015       US       ZW
31414  2015       US       ZW
31415  2015       US       ZW
31416  2015       US       ZW
31417  2015       US       ZW
31418  2015       US       ZW
31419  2015       US       ZW
31420  2015       US       ZW
31421  2015       US       ZW
31422  2015       US       ZW
31423  2015       US       ZW
31424  2015       US       ZW
31425  2015       US       ZW
31426  2015       US       ZW
31427  2015       US       ZW
31428  2015       US       ZW
31429  2015       US       ZW
31430  2015       US       ZW
31431  2015       US       ZW
31432  2015       US       ZW
31433  2015       US       ZW

[31434 rows x 3 columns]

In [8]:
exp_imp_year_count = exp_imp_year.groupby(['Importer','Exporter']).size().reset_index().rename(columns={0:'count'})

In [9]:
sort_by_count = exp_imp_year_count.sort('count', ascending=False)

In [10]:
sort_by_count

     Importer Exporter  count
2034       US       ZA   1623
2036       US       ZW   1121
1940       US       GB    679
2135       ZA       ZW    452
574        DE       ZW    421
1914       US       CA    416
708        ES       ZW    355
875        GB       ZA    352
706        ES       ZA    326
1938       US       FR    312
1912       US       BW    288
321        CA       US    269
105        AT       ZW    257
872        GB       US    253
571        DE       ZA    248
346        CH       DE    231
327        CA       ZW    228
158        AU       ZA    223
1928       US       DE    219
877        GB       ZW    215
351        CH       FR    212
794        FR       ZW    211
2101       ZA       BW    206
792        FR       ZA    185
1530       NZ       ZA    183
285        CA       GB    183
325        CA       ZA    183
440        CN       ZW    180
1110       IT       ZW    175
1108       IT       ZA    168
...       ...      ...    ...
468        CY       GR      1
491        CZ       SN      1
1366       MW       IN      1
1340       MO       HU      1
1342       MO       PT      1
1346       MR       AE      1
1347       MR       ZA      1
1348       MR       ZW      1
489        CZ       PL      1
1356       MT       TG      1
1359       MT       ZW      1
1360       MU       CH      1
486        CZ       MC      1
485        CZ       IT      1
1365       MV       FR      1
484        CZ       HU      1
469        CY       TZ      1
1371       MX       BE      1
1375       MX       DE      1
481        CZ       GA      1
478        CZ       CM      1
476        CZ       CA      1
1382       MX       IL      1
1385       MX       LA      1
1388       MX       NL      1
1389       MX       PA      1
1391       MX       SV      1
470        CY       US      1
1394       MX       UY      1
0          AD       DE      1

[2160 rows x 3 columns]

In [11]:
US_import = sort_by_count.loc[sort_by_count['Importer'] == 'US']

In [12]:
US_import

     Importer Exporter  count
2034       US       ZA   1623
2036       US       ZW   1121
1940       US       GB    679
1914       US       CA    416
1938       US       FR    312
1912       US       BW    288
1928       US       DE    219
2022       US       TZ    166
1988       US       NG    152
1906       US       BE    150
2031       US       XX    134
1983       US       MX    132
1959       US       IT    123
1963       US       JP    108
1900       US       AT    103
1989       US       NL     87
1918       US       CH     87
1964       US       KE     82
1950       US       HK     75
2035       US       ZM     69
1934       US       ES     63
1921       US       CM     60
1901       US       AU     57
1899       US       AR     54
1944       US       GH     54
1991       US       NZ     45
1929       US       DK     43
1935       US       ET     42
1956       US       IL     35
2018       US       TH     34
...       ...      ...    ...
1978       US       MK      2
1977       US       MC      2
1937       US       FJ      1
1981       US       MU      1
1974       US       LS      1
1896       US       AM      1
1897       US       AN      1
1969       US       KY      1
1987       US       NE      1
1992       US       OM      1
1965       US       KH      1
1952       US       HT      1
1949       US       GW      1
1926       US       CY      1
1943       US       GF      1
1941       US       GD      1
1933       US       ER      1
1902       US       AW      1
1903       US       AZ      1
1904       US       BA      1
1905       US       BB      1
1907       US       BG      1
1960       US       JE      1
1913       US       BY      1
2012       US       SV      1
2025       US       US      1
2015       US       TC      1
2013       US       SY      1
2032       US       YE      1
2028       US       VG      1

[142 rows x 3 columns]

In [13]:
ZA_import = sort_by_count.loc[sort_by_count['Importer'] == 'ZA']

In [14]:
ZA_import

     Importer Exporter  count
2135       ZA       ZW    452
2101       ZA       BW    206
2130       ZA       TZ     93
2123       ZA       MZ     92
2112       ZA       GB     48
2105       ZA       CM     28
2121       ZA       MW     19
2134       ZA       ZM     19
2131       ZA       US     13
2099       ZA       AU     11
2110       ZA       FR     11
2107       ZA       DE     11
2116       ZA       KE      7
2114       ZA       IT      6
2111       ZA       GA      5
2115       ZA       JP      5
2113       ZA       HK      5
2104       ZA       CI      4
2128       ZA       SZ      4
2124       ZA       NL      4
2125       ZA       NZ      4
2117       ZA       KR      3
2100       ZA       BE      3
2103       ZA       CH      3
2109       ZA       ES      2
2108       ZA       DK      2
2102       ZA       CA      2
2098       ZA       AE      2
2132       ZA       XX      2
2133       ZA       ZA      2
2127       ZA       PT      1
2122       ZA       MX      1
2126       ZA       PL      1
2129       ZA       TG      1
2106       ZA       CN      1
2120       ZA       ML      1
2119       ZA       LS      1
2118       ZA       LK      1

In [15]:
ZW_import = sort_by_count.loc[sort_by_count['Importer'] == 'ZW']

In [16]:
ZW_import

     Importer Exporter  count
2144       ZW       BW     30
2157       ZW       ZA     29
2152       ZW       MZ     23
2151       ZW       MW      9
2155       ZW       US      7
2159       ZW       ZW      4
2158       ZW       ZM      3
2150       ZW       KR      3
2156       ZW       XX      3
2145       ZW       CN      2
2143       ZW       BE      2
2147       ZW       GB      2
2154       ZW       TZ      2
2149       ZW       KE      1
2148       ZW       JP      1
2153       ZW       SG      1
2146       ZW       DE      1

In [17]:
GB_import = sort_by_count.loc[sort_by_count['Importer'] == 'GB']

In [18]:
GB_import

    Importer Exporter  count
875       GB       ZA    352
872       GB       US    253
877       GB       ZW    215
802       GB       AU    106
811       GB       CH     95
809       GB       CA     64
854       GB       NZ     60
839       GB       JP     54
840       GB       KE     37
832       GB       HK     36
807       GB       BW     30
826       GB       GB     29
870       GB       TZ     24
800       GB       AR     23
836       GB       IL     21
838       GB       JE     21
801       GB       AT     18
873       GB       UY     17
850       GB       MZ     16
818       GB       DK     13
825       GB       GA     13
814       GB       CN     12
827       GB       GG     12
860       GB       RU     11
848       GB       MW     10
797       GB       AE     10
864       GB       SG      9
851       GB       NG      6
849       GB       MX      6
805       GB       BR      6
..       ...      ...    ...
847       GB       MU      2
835       GB       IE      2
843       GB       MA      2
821       GB       ET      2
812       GB       CI      2
817       GB       CZ      2
858       GB       PL      2
865       GB       SL      2
856       GB       PE      1
857       GB       PK      1
861       GB       SA      1
867       GB       TH      1
852       GB       NL      1
855       GB       OM      1
820       GB       ES      1
803       GB       BB      1
804       GB       BM      1
810       GB       CG      1
815       GB       CO      1
819       GB       EG      1
822       GB       FI      1
823       GB       FK      1
829       GB       GI      1
830       GB       GM      1
831       GB       GR      1
833       GB       HR      1
842       GB       KW      1
845       GB       ML      1
846       GB       MO      1
799       GB       AO      1

[81 rows x 3 columns]

In [21]:
DE_import = sort_by_count.loc[sort_by_count['Importer'] == 'DE']

In [25]:
CA_import = sort_by_count.loc[sort_by_count['Importer'] == 'CA']

In [28]:
ES_import = sort_by_count.loc[sort_by_count['Importer'] == 'ES']

In [30]:
FR_import = sort_by_count.loc[sort_by_count['Importer'] == 'FR']

In [33]:
BW_import = sort_by_count.loc[sort_by_count['Importer'] == 'BW']

In [35]:
CH_import = sort_by_count.loc[sort_by_count['Importer'] == 'CH']

In [37]:
AT_import = sort_by_count.loc[sort_by_count['Importer'] == 'AT']

In [39]:
CA_export = sort_by_count.loc[sort_by_count['Exporter'] == 'CA']

In [41]:
ES_export = sort_by_count.loc[sort_by_count['Exporter'] == 'ES']

In [43]:
FR_export = sort_by_count.loc[sort_by_count['Exporter'] == 'FR']

In [46]:
US_export = sort_by_count.loc[sort_by_count['Exporter'] == 'US']

In [49]:
US_export[40:]

     Importer Exporter  count
721        FI       US      4
27         AE       US      4
1425       NG       US      3
246        BS       US      3
649        EG       US      3
1284       LU       US      3
222        BM       US      3
1343       MO       US      3
1709       SA       US      3
254        BW       US      3
1869       TZ       US      2
1663       RO       US      2
1885       UA       US      2
1786       SU       US      2
448        CO       US      2
1357       MT       US      2
622        DO       US      2
1049       IS       US      2
915        GT       US      2
1025       IM       US      2
2040       UY       US      2
31         AF       US      1
35         AL       US      1
218        BH       US      1
212        BG       US      1
167        BA       US      1
2054       VE       US      1
1804       SY       US      1
2025       US       US      1
1834       TN       US      1
1822       TH       US      1
1115       JE       US      1
1119       JM       US      1
1128       JO       US      1
1223       KW       US      1
1232       LA       US      1
881        GF       US      1
885        GH       US      1
1633       PY       US      1
1258       LI       US      1
464        CU       US      1
1414       NC       US      1
470        CY       US      1